code/website/Models/MemberContact.cs
/* Copyright 2011 Matt Cosand and others (see AUTHORS.TXT)
 *
 * This file is part of SARTracks.
 *
 *  SARTracks is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  SARTracks is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with SARTracks.  If not, see <http://www.gnu.org/licenses/>.
 */
namespace SarTracks.Website.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Runtime.Serialization;
    using System.ComponentModel.DataAnnotations;

    [DataContract]
    public class MemberContact : SarObject
    {
        [Required]
        [ForeignKey("MemberId")]
        public SarMember Member { get; set; }
        [DataMember]
        public Guid MemberId { get; set; }

        [DataMember]
        public ContactType Type { get; set; }

        [DataMember]
        public string SubType { get; set; }

        [DataMember]
        public int Priority { get; set; }

        [DataMember]
        [Required]
        public string Value { get; set; }

        public void CopyFrom(MemberContact other)
        {
            this.Member = other.Member;
            this.MemberId = (other.Member == null) ? other.MemberId : other.Member.Id;
            this.Type = other.Type;
            this.SubType = other.SubType;
            this.Priority = other.Priority;
            this.Value = other.Value;
        }
    }
}

code/website/ViewModels/NewUnitMemberViewModel.cs
/* Copyright 2011 Matt Cosand and others (see AUTHORS.TXT)
 *
 * This file is part of SARTracks.
 *
 *  SARTracks is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  SARTracks is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with SARTracks.  If not, see <http://www.gnu.org/licenses/>.
 */
namespace SarTracks.Website.ViewModels
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Runtime.Serialization;
    using SarTracks.Website.Models;

    [DataContract]
    public class NewUnitMemberViewModel
    {
        [DataMember]
        public SarMember Member { get; set; }

        [DataMember]
        public Organization Unit { get; set; }

        [DataMember]
        public UnitMembership Membership { get; set; }
    }
}

code/website/Controllers/MembersController.cs
/* Copyright 2011 Matt Cosand and others (see AUTHORS.TXT)
 *
 * This file is part of SARTracks.
 *
 *  SARTracks is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  SARTracks is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with SARTracks.  If not, see <http://www.gnu.org/licenses/>.
 */
namespace SarTracks.Website.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using SarTracks.Website.Models;
    using SarTracks.Website.ViewModels;
    using System.Data.Entity.Infrastructure;
    using SarTracks.Website.Services;

    public class MembersController : ControllerBase
    {
        public MembersController() : base() { }
        public MembersController(AuthIdentityService perms, DataStoreFactory store) : base(perms, store) { }
        
        [HttpGet]
        public ActionResult Detail(Guid q)
        {
            if (!Permissions.HasPermission(PermissionType.ViewMemberStandard, q)) return GetLoginRedirect();

            SarMember model;
            using (var ctx = GetRepository())
            {
                model = ctx.Members.Single(f => f.Id == q);
                if (!Permissions.HasPermission(PermissionType.ViewMemberDetail, q))
                {
                    MembersController.FilterPersonalInfo(new[] { model });
                }
            }

            ViewData["canEdit"] = Permissions.HasPermission(PermissionType.EditMemberContacts, q);
            return View(model);
        }

        [HttpGet]
        public ActionResult ContactManagement(Guid q)
        {
            SarMember member = null;
            using (var ctx = GetRepository())
            {
                member = ctx.Members.Single(f => f.Id == q);
            }
            return PartialView(member);
        }


        public static void FilterPersonalInfo(IEnumerable<SarMember> members)
        {
            foreach (var member in members)
            {
                member.BirthDate = null;
            }
        }

        [HttpPost]
        public DataActionResult SubmitAddress(MemberAddress model)
        {
            if (!Permissions.HasPermission(PermissionType.EditMemberContacts, model.MemberId)) return GetLoginError();
            List<SubmitError> errors = new List<SubmitError>();
            ModelState.Remove("Member");
            ModelState.Remove("Id");

            if (ModelState.IsValid)
            {
                using (var ctx = this.GetRepository())
                {
                    var oldModel = ctx.Members.IncludePaths("Address.Member").Where(f => f.Id == model.MemberId).SelectMany(f => f.Addresses).SingleOrDefault(f => f.Id == model.Id);
                    if (oldModel == null)
                    {
                        ctx.Members.Single(f => f.Id == model.MemberId).Addresses.Add(model);
                    }
                    else
                    {
                        oldModel.CopyFrom(model);
                        if (oldModel.Member == null) oldModel.Member = ctx.Members.Single(f => f.Id == oldModel.MemberId);
                    }
                    ctx.SaveChanges();
                }
            }
            else
            {
                ModelStateToSubmitErrors(errors);
            }

            return Data(new SubmitResult<MemberAddress> { Errors = errors.ToArray(), Result = model });
        }

        [HttpPost]
        public DataActionResult DeleteAddress(Guid q, Guid e)
        {
            if (!Permissions.HasPermission(PermissionType.EditMemberContacts, q)) return GetLoginError();

            using (var ctx = GetRepository())
            {
                var model = ctx.Members.Where(f => f.Id == q).SelectMany(f => f.Addresses).Single(f => f.Id == e);

                ctx.Delete(model);

                ctx.SaveChanges();
            }
            return Data(new SubmitResult<bool> { Result = true });
        }


        [HttpPost]
        public DataActionResult GetAddresses(Guid q)
        {
            if (!Permissions.HasPermission(PermissionType.ViewMemberStandard, q)) return GetLoginError();

            MemberAddress[] model;
            using (var ctx = GetRepository())
            {
                model = ctx.Members.Where(f => f.Id == q).SelectMany(f => f.Addresses)
                    .OrderBy(f => f.Type).ThenBy(f => f.Address.Street)
                    .ToArray();
            }

            return Data(model);
        }

        [HttpPost]
        public DataActionResult DeleteContact(Guid q)
        {
            using (var ctx = GetRepository())
            {
                var model = ctx.Members.SelectMany(f => f.ContactInfo).Single(f => f.Id == q);

                if (!Permissions.HasPermission(PermissionType.EditMemberContacts, model.MemberId)) return GetLoginError();

                ctx.Delete(model);

                ctx.SaveChanges();
            }
            return Data(new SubmitResult<bool> { Result = true });
        }


        [HttpPost]
        public DataActionResult GetContactInfo(Guid q)
        {
            if (!Permissions.HasPermission(PermissionType.ViewMemberStandard, q)) return GetLoginError();

            MemberContact[] model;
            using (var ctx = GetRepository())
            {
                model = ctx.Members.Where(f => f.Id == q).SelectMany(f => f.ContactInfo)
                    .OrderBy(f => f.Type).ThenBy(f => f.Priority).ThenBy(f => f.SubType).ThenBy(f => f.Value)
                    .ToArray();
            }

            return Data(model);
        }

        [HttpPost]
        public DataActionResult SubmitContact(MemberContact model)
        {
            if (!Permissions.HasPermission(PermissionType.EditMemberContacts, model.MemberId)) return GetLoginError();
            List<SubmitError> errors = new List<SubmitError>();
            ModelState.Remove("Member");
            ModelState.Remove("Id");

            if (ModelState.IsValid)
            {
                using (var ctx = this.GetRepository())
                {
                    var oldModel = ctx.Members.IncludePaths("ContactInfo.Member").Where(f => f.Id == model.MemberId).SelectMany(f => f.ContactInfo).SingleOrDefault(f => f.Id == model.Id);
                    if (oldModel == null)
                    {
                        ctx.Members.Single(f => f.Id == model.MemberId).ContactInfo.Add(model);
                    }
                    else
                    {
                        oldModel.CopyFrom(model);
                        
                        if (oldModel.Member == null) oldModel.Member = ctx.Members.Single(f => f.Id == oldModel.MemberId);
                    }
                    ctx.SaveChanges();
                }
            }
            else
            {
                ModelStateToSubmitErrors(errors);
            }
            return Data(new SubmitResult<MemberContact> { Errors = errors.ToArray(), Result = model });
        }

        [HttpPost]
        public DataActionResult GetAllMemberships(Guid q)
        {
            if (!Permissions.HasPermission(PermissionType.ViewMemberBasic, q)) return GetLoginError();

            UnitMembership[] model;

            using (var ctx = GetRepository())
            {
                var orgs = ctx.Organizations.ToArray();

                model = ctx.Members.IncludePaths("Memberships.Unit", "Memberships.Status")
                    .Where(f => f.Id == q)
                    .SelectMany(f => f.Memberships)
                    .OrderBy(f => f.Organization.Name).ThenByDescending(f => f.Status).ToArray();

                foreach (var row in model)
                {

                }
            }

            return Data(model);
        }

        [HttpPost]
        [Authorize]
        public DataActionResult GetDesignators(Guid q, DateTime? when)
        {
            if (!Permissions.HasPermission(PermissionType.ViewMemberBasic, q)) return GetLoginError();

            when = when ?? DateTime.Now;

            Dictionary<string, List<Guid>> designators = new Dictionary<string, List<Guid>>();
            Dictionary<Guid, string> lookup = new Dictionary<Guid, string>();

            using (var ctx = GetRepository())
            {
                Organization[] orgs = ctx.Organizations.ToArray();

                List<UnitMembership> memberships = ctx.Members
                    .Where(f => f.Id == q)
                    .SelectMany(f => f.Memberships)
                    .Where(f => f.Status.IsActive && f.Start < when && (f.Finish == null || f.Finish < when)).ToList();

                int count;
                int newCount = 0;

                // Iterate through the current members.
                // If the worker number is not blank, keep track of it in the list/tables
                // If the number is blank, then retrieve it from the linked org and keep track of where it came from

                do
                {
                    count = newCount;
                    int i = 0;
                    for (i = 0; i < memberships.Count; )
                    {
                        var membership = memberships[i];

                        if (!string.IsNullOrWhiteSpace(membership.WorkerNumber))

code/website/Views/Members/ContactManagement.cshtml
@model SarTracks.Website.Models.SarMember
@using SarTracks.Website.Models;
@* BEGIN MANAGEMENT *@
<div id="ContactDialog" title="Create Member Contact" style="display: none;">
    <form method="post" id="ContactForm" action="#"> 
    <p name="validateTips" class="validmsg" style="display:none;"></p>
    <input type="hidden" name="MemberId" data-bind="value: MemberId" />
    <input type="hidden" name="Id" data-bind="value: Id" />
    <div class="editor-label"><label for="Type">Type</label></div>
    <div class="editor-field">
    <select data-bind="options: [0,1,2], optionsText: function(f) { return contactTypes[f]; }, value: Type" data-val="true" data-val-required="The Type field is required." name="Type">
    </select>
    <span class="validmsg" validates="Type"></span>
    </div>

    <div data-bind="visible: subTypes[Type()] != null">
    <label for="SubType">SubType</label>
    <div class="editor-field">
    <select id="SubType" name="SubType" data-bind="value: SubType, options: subTypes[Type()]"></select>
    <span class="validmsg" validates="SubType"></span>
    </div>
    </div>

    <div class="editor-label">
    <label for="Value">Value</label>
    </div>
    <div class="editor-field">
    <input data-bind="value: Value" name="Value" type="text" class="required" />
    <span class="validmsg" validates="Value"></span>
    </div>
    </form>
</div>

<div id="AddressDialog" title="Create Member Address" style="display: none;">
    <form method="post" id="AddressForm" action="#">
    <p name="validateTips" class="validmsg" style="display:none;"></p>
    <input type="hidden" name="MemberId" data-bind="value: MemberId" />
    <input type="hidden" name="Id" data-bind="value: Id" />
    <div class="editor-label"><label for="Type">Type</label></div>
    <div class="editor-field">
        <select data-bind="options: [0,1], optionsText: function(f) { return addressTypes[f]; }, value: Type" name="Type">
        </select>
        <span class="validmsg" validates="Type"></span>
    </div>
    <div class="editor-label"><label for="Address_Street">Street</label></div>
    <div class="editor-field">
        <input name="Address.Street" type="text" data-bind="value: Address.Street" />
        <span class="validmsg" validates="Address.Street"></span>
    </div>
    <div class="editor-label"><label for="Address_City">City</label></div>
    <div class="editor-field">
        <input name="Address.City" type="text" data-bind="value: Address.City" />
        <span class="validmsg" validates="Address.City"></span>
    </div>
    <div class="editor-label"><label for="Address_State">State</label></div>
    <div class="editor-field">
        <input name="Address.State" type="text" data-bind="value: Address.State" />
        <span class="validmsg" validates="Address.State"></span>
    </div>
    <div class="editor-label"><label for="Address_Zip">Zip</label></div>
    <div class="editor-field">
        <input name="Address.Zip" type="text" data-bind="value: Address.Zip" />
        <span class="validmsg" validates="Address.Zip"></span>
    </div>
    </form>
</div>
<script type="text/javascript">
    var contactModel;
    var addressModel;

    $(document).ready(function () {
        setupFormDialog2($('#ContactDialog'), 300, 450, "Save Member Contact", '@Url.Action("SubmitContact")', function (data) { loadContacts(); });
        setupFormDialog2($('#AddressDialog'), 350, 350, "Save Address", '@Url.Action("SubmitAddress")', function (data) { loadAddresses(); });
    });
</script>

@* END MANAGEMENT *@

code/website/Views/Members/Detail.cshtml
@* Copyright 2011 Matt Cosand and others (see AUTHORS.TXT)
 *
 * This file is part of SARTracks.
 *
 *  SARTracks is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  SARTracks is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with SARTracks.  If not, see <http://www.gnu.org/licenses/>.
 *@
@model SarTracks.Website.Models.SarMember

@{
    ViewBag.Title = "Details";   
}

  <div id="card" style="padding: 2px; width: 25em; border: solid 1px black; ">

    <div class="wac_Field" style="font-weight:bold; text-align:center; text-transform:uppercase; margin-bottom:.3em">Field</div>
    <div style="margin:.2em .2em 0 0; position:relative;">
      <div style="float:left;"><img alt="Badge Photo" src="@Url.Action("Photo", new { q = @Model.Id })" style="border:2px solid black; height:12em; width:9em;" title="Badge Photo" /></div>
      <div style="float:left; white-space:nowrap; margin-left:.4em; height:12em;">
        <div id="cardname" style="font-weight:bold; font-size:1.2em;">@Model.FirstName @Model.LastName</div>
<!--        <table>
        <tr><td style="text-align:right">DEM#</td><td>7031</td></tr>
        
          <tr><td style="text-align:right">BirthDate</td><td>11/3/1978</td></tr>
        
        </table>
        -->
        <div id="designators"></div>
        @Html.Raw(Model.BirthDate.HasValue ? ("Birthday: " + Model.BirthDate.Value.ToString("MM/dd/yyyy") + "<br/>") : "")
        
         <div style="position:absolute; bottom:.2em; right:.2em;">
 <!--       Background Check: <br />
        WAC Expiration: <span class="wac-status">Loading...</span><br />
        <a href="/Members/PhotoUpload/3ed54156-b4c6-4ea2-a1c4-58e98be0b93b" onclick="window.open(this.href, 'photo', 'width=540,height=400,scrollbars=1'); return false;" target="_blank">Photo</a>
        <a href="/Members/Edit/3ed54156-b4c6-4ea2-a1c4-58e98be0b93b" onclick="window.open(this.href, 'edit', 'width=540,height=300,scrollbars=1'); return false;" target="_blank">Edit</a>

        <a href="/Members/Delete/3ed54156-b4c6-4ea2-a1c4-58e98be0b93b">Delete</a>
        -->
        </div>
      </div>
      <div style="clear:both"></div>
    </div>
  </div>

  <h3>Addresses:</h3>
  @Html.Partial("MemberAddresses", Model)


  <h3>Contact Information:</h3>
  @Html.Partial("MemberContacts", Model)

  <script type="text/javascript">
      function loadMemberships() {
        $('#designators').html('Loading ...');
        $.ajax({ type: 'POST', url: '@Url.Action("GetDesignators")', data: { q: '@Model.Id' }, dataType: 'json',
            success: function (data) {
                var div = $('#designators').html('');

                for (var i in data)
                {
                    div.append(data[i].Issuer + '#: ' + data[i].Designator + '<br/>');
                }
            }
         });
      }


      $(document).ready(function () {
          loadMemberships();
      });
  </script>

code/website/Views/Members/MemberAddresses.cshtml
@* Copyright 2011 Matt Cosand and others (see AUTHORS.TXT)
 *
 * This file is part of SARTracks.
 *
 *  SARTracks is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  SARTracks is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with SARTracks.  If not, see <http://www.gnu.org/licenses/>.
 *@
@model SarTracks.Website.Models.SarMember
@using SarTracks.Website.Models

@{ bool canEdit = (bool)ViewData["canEdit"]; }
<table id="AddressTable" class="data-table" cellspacing="0" data-bind="triggerUpdate: rows">
<tbody data-bind="template: { name: 'addressTableTmpl', foreach: rows }">
</tbody>
</table>

<script type="text/html" id="addressTableTmpl">
  <tr>
    <td><strong data-bind="text: addressTypes[Type()]"></strong></td>
    <td data-bind="text: Address.Street()+', '+Address.City()+', '+Address.State()+' '+Address.Zip()"></td>
    @if (canEdit)
    {
      <td>
        <img class="img-button EditAddress" src="@Url.Content("~/Content/images/edit.png")" />
        <img class="img-button DeleteAddress" data-bind="attr: { delid: Id(), delmsg: Type() }" src="@Url.Content("~/Content/images/delete.png")" />
      </td>
    }
  </tr>     
</script>
<span class="AddAddress ButtonLink">Add Address</span>

<script type="text/javascript">
  var addressTypes = ['@Html.Raw(string.Join("', '", Enum.GetNames(typeof(MemberAddressType))))'];
  var addressList = null;

  function loadAddresses()
  {
    $.ajax({type: 'POST', url: '@Url.Action("GetAddresses")', data: { q: '@Model.Id' }, dataType: 'json', 
           success: function (data) {
               var t = $('#AddressTable');
               if (addressList == null) {
                   addressList = ko.mapping.fromJS({ rows: data });
                   ko.applyBindings(addressList, t[0]);
               } else {
                   ko.mapping.fromJS({ rows: data }, { 'rows': { 'key': function (data) { return ko.utils.unwrapObservable(data.Id); }}}, addressList);
               }
               colorTable(t);
           }
       });
   }

   $(document).ready(function() {
     @if (canEdit)
     {
       <text>
       $(".AddAddress").click(function() {
          loadManagement('@Url.Action("ContactManagement")', {q: '@Model.Id' }, function () {
            addressModel = ko.mapping.fromJS({ Id: null, MemberId: '@Model.Id',Type: 1, Address: {Street: null, City: null, State: null, Zip: null }});
            ko.applyBindings(addressModel, $('#AddressDialog')[0]);
            $('#AddressDialog').dialog("open");
          });
        });

        wireEditDelete('Address', '@Url.Action("DeleteAddress")', loadAddresses);
        </text>
     }
     loadAddresses();
     loadManagement('@Url.Action("ContactManagement")', {q: '@Model.Id' }, function () { });
   });
</script>

code/website/Views/Members/NewUnitMemberForm.cshtml
@* Copyright 2011 Matt Cosand and others (see AUTHORS.TXT)
 *
 * This file is part of SARTracks.
 *
 *  SARTracks is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  SARTracks is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with SARTracks.  If not, see <http://www.gnu.org/licenses/>.
 *@
@model SarTracks.Website.ViewModels.NewUnitMemberViewModel
@using SarTracks.Website.Models;
@{
    ViewBag.Title = "Member Details";
}

@using (Html.BeginForm("NewUnitMember", "Members", FormMethod.Post, new { id = "NewMemberForm" }))
{
@Html.HiddenFor(f => f.Member.Id)
@Html.HiddenFor(f => f.Unit.Id)

    @Html.ValidationSummary(true, "Member could not be saved. Please correct the errors and try again.")
    <div class="editor-label">
    @Html.LabelFor(m => m.Member.FirstName)
    </div>
    <div class="editor-field">
    @Html.TextBoxFor(f => f.Member.FirstName)
    @Html.ValidationMessageFor(m => m.Member.FirstName)
    </div>

    <div class="editor-label">
    @Html.LabelFor(m => m.Member.LastName)
    </div>
    <div class="editor-field">
    @Html.TextBoxFor(f => f.Member.LastName)
    @Html.ValidationMessageFor(m => m.Member.LastName)
    </div>
    
    <div class="editor-label">
    @Html.LabelFor(m => m.Member.Gender)
    </div>
    <div class="editor-field">
    @Html.DropDownListFor(m => m.Member.Gender, new SelectList(Enum.GetNames(typeof(Gender)), Model.Member.Gender))
    @Html.ValidationMessageFor(m => m.Member.Gender)
    </div>
            
    <div class="editor-label">
    @Html.LabelFor(m => m.Member.BirthDate)
    </div>
    <div class="editor-field">
    @Html.EditorFor(m => m.Member.BirthDate)
    @Html.ValidationMessageFor(m => m.Member.BirthDate)
    </div>
    <br />
    <fieldset>
        <legend>Membership with @Model.Unit.Name</legend>
        <div class="editor-label">
        @Html.LabelFor(m => m.Membership.Status, "Current Status")
        @Html.DropDownListFor(m => m.Membership.Status.Id, new SelectList(Model.Unit.UnitStatusTypes.OrderByDescending(f => f.IsActive).ThenByDescending(f => f.IsMissionQualified), "Id", "Name", Model.Membership.Status.Id))
        @Html.ValidationMessageFor(m => m.Membership.Status)
        </div>

        <div class="editor-label">
        @Html.LabelFor(m => m.Membership.Start, "Effective Date")
        @Html.EditorFor(m => m.Membership.Start)
        @Html.ValidationMessageFor(m => m.Membership.Start)
        </div>
    </fieldset>
}
@*<script type="text/javascript">
    var subTypes = { 'Phone': ['Cell', 'Home', 'Work', 'Pager', 'Other'],
        'Email': null,
        'Radio': ['HAM']
    };

    function contact_updateSubType(type, selected) {
        var select = $("#SubType").html('');

        for (option in subTypes[type]) {
            var o = $('<option>' + subTypes[type][option] + '</option>');
            if (o[0].value == selected) o.attr('selected', 'selected');
            select.append(o);
        }
        select[0].disabled = (subTypes[type] == null || subTypes[type].length == 0);
    }

    $(document).ready(function () {
        contact_updateSubType('@Model.Type', '@Model.SubType');
    });
</script>
*@