code/website/Models/Organization.cs
/* Copyright 2011 Matt Cosand and others (see AUTHORS.TXT)
 *
 * This file is part of SARTracks.
 *
 *  SARTracks is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  SARTracks is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with SARTracks.  If not, see <http://www.gnu.org/licenses/>.
 */
namespace SarTracks.Website.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Data.Spatial;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.Serialization;

    [DataContract]
    [KnownType(typeof(SarUnit))]
    public class Organization : SarObject
    {
        public Organization() : base()
        {
            this.MailingAddress = new Address();
            this.JoinKey = Guid.NewGuid();
            this.UnitStatusTypes = new List<UnitStatusType>();
            this.Memberships = new List<UnitMembership>();

            this.LinksFromOrgs = new List<OrganizationLink>();
            this.LinksToOrgs = new List<OrganizationLink>();
        }

        [Required]
        [DataMember]
        public string Name { get; set; }

        [DataMember]
        public string LongName { get; set; }

        [DataMember]
        public bool IsApproved { get; set; }

        [DataMember]
        public Guid JoinKey { get; set; }

        [DataMember]
        public string AdminAccount { get; set; }

        [DataMember]
        public Address MailingAddress { get; set; }

        public WellKnownPlace PrimaryCoverage { get; set; }
        public string PrimaryCoverageName { get; set; }
        public DbGeography PrimaryCoverageGeo { get; set; }

        public WellKnownPlace MouCoverage { get; set; }
        public string MouCoverageName { get; set; }
        public DbGeography MouCoverageGeo { get; set; }

        [Required]
        public string TimeZone { get; set; }
        
        public ICollection<UnitStatusType> UnitStatusTypes { get; set; }

        public ICollection<UnitMembership> Memberships { get; set; }

        [InverseProperty("FromOrganization")]
        public ICollection<OrganizationLink> LinksToOrgs { get; set; }

        [InverseProperty("ToOrganization")]
        public ICollection<OrganizationLink> LinksFromOrgs { get; set; }

        public bool GetsWorkerNumberFromAuthoritative { get; set; }
    }
}

code/website/Controllers/HomeController.cs
/* Copyright 2011 Matt Cosand and others (see AUTHORS.TXT)
 *
 * This file is part of SARTracks.
 *
 *  SARTracks is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  SARTracks is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with SARTracks.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace SarTracks.Website.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;
    using SarTracks.Website.Models;
    using SarTracks.Website.ViewModels;
    using SarTracks.Website.Services;

    public class HomeController : ControllerBase
    {
        public HomeController() : base() { }
        public HomeController(AuthIdentityService perms, DataStoreFactory factory) : base(perms, factory) { }

        public ActionResult Index()
        {
            Dictionary<Guid, string> orgs = this.GetUsersDatabaseOrgs();
            bool auth = Permissions.IsAuthenticated;
            bool hasAccount = Permissions.IsUser;
            bool hasMember = Permissions.User != null && Permissions.User.MemberId != null;

            HomePageViewModel model = new HomePageViewModel
            {
                LoggedIn = auth,
                HasAccount = hasAccount,
                LinkedMember = (Permissions.User == null || Permissions.User.MemberId == null) ? Guid.Empty : Permissions.User.MemberId.Value,
                MyDetails = hasMember,
                MyTraining = hasMember,
                MyMissions = hasMember,
                PublicMapping = true,
                PublicReports = true,
                MyUnits = orgs.Select(f => new HomePageUnitViewModel {
                    Id = f.Key, 
                    Name = f.Value,
                    Permissions = string.Format("{0}{1}{2}{3}",
                        Permissions.HasPermission(PermissionType.ViewOrganizationBasic, f.Key) ? "*" : " ",
                        Permissions.HasPermission(PermissionType.ViewOrganizationBasic, f.Key) ? "*" : " ",
                        Permissions.HasPermission(PermissionType.ViewOrganizationBasic, f.Key) ? "*" : " ",
                        Permissions.HasPermission(PermissionType.AdminOrganization, f.Key) ? "*" : " ")
                }).ToArray()
            };

            ViewData["hideMenu"] = true;
            return View(model);
        }

        /// <summary>
        /// code sandbox
        /// </summary>
        /// <param name="q"></param>
        /// <returns></returns>
        public ActionResult Test(string q)
        {
            string filename = "test";

            ExcelFileType fileType;
            if (!Enum.TryParse<ExcelFileType>(q, true, out fileType)) fileType = ExcelFileType.XLSX;

            ExcelFile file = ExcelService.Create(fileType);

            var sheet = file.CreateSheet("Sheet1");

            sheet.CellAt(0, 4).SetValue(77);

            sheet.CellAt(0, 0).SetValue(sheet.CellAt(0, 1).NumericValue ?? -42);

            System.IO.MemoryStream ms = new System.IO.MemoryStream();
            file.Save(ms);
            ms.Seek(0, System.IO.SeekOrigin.Begin);
            return this.File(ms, file.Mime, file.AddExtension(filename));
        }

        public ActionResult About()
        {
            return View();
        }
    }
}

code/website/Controllers/OrganizationsController.cs
/* Copyright 2011 Matt Cosand and others (see AUTHORS.TXT)
 *
 * This file is part of SARTracks.
 *
 *  SARTracks is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  SARTracks is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with SARTracks.  If not, see <http://www.gnu.org/licenses/>.
 */
namespace SarTracks.Website.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using System.Web.Security;
    using SarTracks.Website.Models;
    using SarTracks.Website.Services;
    using SarTracks.Website.ViewModels;

    public class OrganizationsController : ControllerBase
    {
        public const string VIEWDATA_LIST_TIMEZONES = "listTimezones";
        public const string VIEWDATA_LIST_VISIBILITY = "listVisibility";

        public OrganizationsController() : base() { }
        public OrganizationsController(AuthIdentityService perms, DataStoreFactory factory) : base(perms, factory) { }

        [HttpGet]
        [Authorize]
        public ActionResult Create()
        {
            string selectedRole = AuthIdentityService.USERS_ROLE;
            var arguments = new NewOrganizationViewModel
            {
                Org = new SarUnit { AdminAccount = Permissions.UserLogin },
                Visibility = selectedRole
            };
            ViewData[OrganizationsController.VIEWDATA_LIST_TIMEZONES] = new SelectList(TimeZoneInfo.GetSystemTimeZones().Select(f => new { Id = f.Id, Name = string.Format("[{0}{1:hh\\:mm}] {2}", (f.BaseUtcOffset.TotalHours < 0) ? '-' : '+', f.BaseUtcOffset, f.StandardName) }), "Id", "Name");
            ViewData[OrganizationsController.VIEWDATA_LIST_VISIBILITY] = new SelectList(new[] { AuthIdentityService.EVERYONE_ROLE, AuthIdentityService.USERS_ROLE, AuthIdentityService.MISSION_VIEWERS_ROLE, "Restricted" }, selectedRole);
            return View(arguments);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Create(NewOrganizationViewModel model)
        {
            var org = model.Org;
            if (ModelState.IsValid)
            {
                using (var ctx = GetRepository())
                {
                    ctx.Users.Attach(Permissions.User);

                    // Default status types
                    org.UnitStatusTypes.Add(new UnitStatusType { Name = "Active", IsActive = true, IsMissionQualified = true, Organization = org });
                    org.UnitStatusTypes.Add(new UnitStatusType { Name = "Inactive", IsActive = false, IsMissionQualified = false, Organization = org });

                    ctx.Organizations.Add(org);

                    ctx.InitializeOrganizationSecurity(org, Permissions.User);

                    ctx.SaveChanges();

                    return RedirectToAction("Home", new { q = org.Id });
                }
            }

            // If we got this far, something failed - redisplay form
            return View(model);
        }

        [Authorize]
        [HttpPost]
        public DataActionResult DoDeleteOrganization(Guid q)
        {
            List<SubmitError> errors = new List<SubmitError>();
            bool result = false;
            Organization model = null;
            using (var ctx = GetRepository())
            {
                model = ctx.Organizations.SingleOrDefault(f => f.Id == q);
                if (model != null)
                {
                    ctx.Organizations.Remove(model);
                    ctx.SaveChanges();
                    result = true;
                }
                else
                {
                    errors.Add(new SubmitError { Error = "Organization not found", Id = new [] { q } });
                }
            }
            return Data(new SubmitResult<bool> { Result = result, Errors = errors.ToArray() });
        }

        [Authorize]
        [HttpGet]
        public ActionResult Home(Guid q)
        {
            Organization model = null;
            using (var ctx = GetRepository())
            {
                model = ctx.Organizations.SingleOrDefault(f => f.Id == q);

                if (!model.IsApproved)
                {
                    ViewData["warning"] = "Your organization has not been approved by the site administrator, and will not be displayed in site reports.";
                }
            }


            return View(model);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Settings(Guid q)
        {
            Organization model = null;
            using (var ctx = GetRepository())
            {
                model = ctx.Organizations.SingleOrDefault(f => f.Id == q);

                if (!model.IsApproved)
                {
                    ViewData["warning"] = "Your organization has not been approved by the site administrator, and will not be displayed in site reports.";
                }
            }

            return View(model);
        }

        [Authorize]
        [HttpGet]
        public ActionResult StatusManagement(Guid q)
        {
            if (!Permissions.HasPermission(PermissionType.ViewOrganizationDetail, q)) return GetLoginError();

            UnitStatusType model = new UnitStatusType();
            using (var ctx = GetRepository())
            {
                var org = ctx.Organizations.Single(f => f.Id == q);
                model.Organization = org;
                model.OrganizationId = org.Id;
            }

            return PartialView(model);
        }

        [HttpPost]
        public DataActionResult SetOrganizationApproved(Guid q, bool approved)
        {
            List<SubmitError> errors = new List<SubmitError>();
            Organization org = null;
            using (var ctx = GetRepository())
            {
                org = ctx.Organizations.SingleOrDefault(f => f.Id == q);
                if (org == null)
                {
                    errors.Add(new SubmitError { Property = q.ToString(), Error = "Organization Not Found" });
                }
                else
                {
                    org.IsApproved = approved;
                    ctx.SaveChanges();
                }
            }

            return Data(new SubmitResult<Organization> { Errors = errors.ToArray(), Result = org });
        }

        [HttpGet]
        public ActionResult List()
        {
            if (!Permissions.HasPermission(PermissionType.SiteAdmin, null)) return GetLoginRedirect();
            return View();
        }

        [HttpPost]
        public DataActionResult GetList()
        {
            //if (!Permissions.IsInRole(AuthIdentityService.ADMIN_ROLE)) return GetLoginError();

            Organization[] model;
            using (var ctx = GetRepository())
            {
                model = ctx.Organizations
                    .OrderBy(f => f.LongName).AsEnumerable()
                    .Where(f => Permissions.HasPermission(PermissionType.ListOrganization, f.Id)).ToArray();
            }
            return Data(model);
        }

        [HttpGet]
        [Authorize]
        public ActionResult StatusTypes(Guid q)
        {
            if (!Permissions.HasPermission(PermissionType.ViewOrganizationDetail, q)) return GetLoginRedirect();

            Organization unit;
            using (var ctx = GetRepository())
            {
                unit = (Organization)ctx.Organizations.SingleOrDefault(f => f.Id == q);
            }
            return View(unit);
        }

        [HttpGet]
        [Authorize]
        public ActionResult CreateStatus(Guid q)
        {
            if (!Permissions.HasPermission(PermissionType.AdminOrganization, q)) return GetLoginRedirect();

            UnitStatusType model;
            using (var ctx = GetRepository())
            {
                model = new UnitStatusType
                {
                    //Organization = (SarUnit)ctx.Organizations.Single(f => f.Id == q)
                };
            }
            ViewBag.OrgId = q;
            return PartialView("StatusForm", model);
        }

        [HttpGet]
        [Authorize]
        public ActionResult EditStatus(Guid q, Guid status)
        {
            if (!Permissions.HasPermission(PermissionType.AdminOrganization, q)) return GetLoginRedirect();
            UnitStatusType model;
            using (var ctx = GetRepository())
            {
                model = ctx.Organizations.Where(f => f.Id == q).SelectMany(f => f.UnitStatusTypes).Where(f => f.Id == status).Single();
            }
            ViewBag.OrgId = q;
            return PartialView("StatusForm", model);
        }

        [HttpPost]
        [Authorize]
        public DataActionResult SaveStatus(Guid q, UnitStatusType model)
        {
            if (!Permissions.HasPermission(PermissionType.AdminOrganization, q)) return GetLoginError();

            SubmitResult<UnitStatusType> result = new SubmitResult<UnitStatusType>();
            ModelState.Remove("Organization");
            if (ModelState.IsValid)
            {
                using (var ctx = GetRepository())
                {
                    var oldModel = ctx.Organizations.Where(f => f.Id == q).SelectMany(f => f.UnitStatusTypes).SingleOrDefault(f => f.Id == model.Id);

code/website/Views/Organizations/Create.cshtml
@* Copyright 2011 Matt Cosand and others (see AUTHORS.TXT)
 *
 * This file is part of SARTracks.
 *
 *  SARTracks is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  SARTracks is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with SARTracks.  If not, see <http://www.gnu.org/licenses/>.
 *@
@model SarTracks.Website.ViewModels.NewOrganizationViewModel
@using SarTracks.Website
@using SarTracks.Website.Controllers
@{
    ViewBag.Title = "Create SAR Organization";
}
@*<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
*@<h2>
    Create a New Organization</h2>
<p>
    Complete the following form to register a new organization. The application will
    be reviewed, and an email will be sent to you after verification.</p>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true, "Account creation was unsuccessful. Please correct the errors and try again.")
    <div>
        <fieldset>
            <legend>Organization Information</legend>
            <div class="editor-label">
                @Html.LabelFor(m => m.Org.LongName)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(m => m.Org.LongName)
                @Html.ValidationMessageFor(m => m.Org.LongName)
            </div>

            <div class="editor-label">
                @Html.LabelFor(m => m.Org.Name)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(m => m.Org.Name)
                @Html.ValidationMessageFor(m => m.Org.Name)
            </div>

            <div class="editor-label">
                @Html.LabelFor(m => m.Org.TimeZone)
            </div>
            <div class="editor-field">
                @Html.DropDownListFor(m => m.Org.TimeZone, (SelectList)ViewData[OrganizationsController.VIEWDATA_LIST_TIMEZONES])
                @Html.ValidationMessageFor(m => m.Org.LongName)
            </div>

            <div class="editor-lable">
            @Html.LabelFor(m => m.Visibility)
            </div>
            <div class="editor-field">
                @Html.DropDownListFor(m => m.Visibility, (SelectList)ViewData[OrganizationsController.VIEWDATA_LIST_VISIBILITY])
                @Html.ValidationMessageFor(m => m.Visibility)
            </div>

            <div class="editor-label">
                @Html.LabelFor(m => m.Org.AdminAccount)
            </div>
            <div class="editor-field">
                @Model.Org.AdminAccount
            </div>


            <p>
                <input type="submit" value="Register" />
            </p>
        </fieldset>
    </div>
}

code/website/Views/Organizations/Home.cshtml
@* Copyright 2011 Matt Cosand and others (see AUTHORS.TXT)
 *
 * This file is part of SARTracks.
 *
 *  SARTracks is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  SARTracks is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with SARTracks.  If not, see <http://www.gnu.org/licenses/>.
 *@
@model SarTracks.Website.Models.Organization
@using SarTracks.Website.ViewModels

@{
    ViewBag.Title = "Home";
    ViewBag.Heading = Model.LongName;
}

<div>
@{Html.RenderPartial("NavButton", new NavButtonViewModel { Text = "Roster", Href = Url.Action("Roster", "Units", new { q = Model.Id }), Enabled = true, ImageName = "phone_book", ImageAlt = "phone book" });}
@{Html.RenderPartial("NavButton", new NavButtonViewModel { Text = "Training", Href = Url.Action("Training", "Units", new { q = Model.Id }), Enabled = true, ImageName = "easel", ImageAlt = "Easel" });}
@{Html.RenderPartial("NavButton", new NavButtonViewModel { Text = "Missions", Href = Url.Action("Missions", "Units", new { q = Model.Id }), Enabled = true, ImageName = "mission", ImageAlt = "Mission Notebook" });}
</div>

code/website/Views/Organizations/List.cshtml
@* Copyright 2011 Matt Cosand and others (see AUTHORS.TXT)
 *
 * This file is part of SARTracks.
 *
 *  SARTracks is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  SARTracks is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with SARTracks.  If not, see <http://www.gnu.org/licenses/>.
 *@
@{
    ViewBag.Title = "Registered Organizations";
    ViewBag.Heading = "Registered Organizations";
}
<table id="table" class="data-table" cellspacing="0">
    <thead>
        <tr>
            <th>
            </th>
            <th>
                Name
            </th>
            <th>Full Name</th>
            <th>
                Admin
            </th>
            <th>
                Approved
            </th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>
<script type="text/javascript">
    function load() {
        $('#table body').html('<tr><td colspan="4" style="text-align:center;">Loading...</td></tr>');

        $.ajax({ type: 'POST', url: '@Url.Action("GetList")', data: null, dataType: 'json',
            success: function (data) {
                var table = $('#table tbody').html('');
                for (var i in data) {
                    var row = data[i];

                    var html =
                    "<tr><td><img src=\"@Url.Content("~/Content/images/delete.png")\" onclick=\"deleteOrg('" + row.Id + "', '" + row.Name + "');\" />" +
                    "</td><td>" + row.Name +
                    '</td><td><a href="@Url.Action("Home", "Organizations")/' + row.Id + '">' + row.LongName + '</a>' +
                    "</td><td>" + row.AdminAccount +
                    '</td><td><a href="#" onclick="setApproved(\'' + row.Id + '\',\'' + row.Name + '\','  + !row.IsApproved + ')">' + row.IsApproved + '</a>' +
                    "</td></tr>";

                    table.append(html);
                }
                updateSort($('#table'));
            }
        });
    }

    function setApproved(id, name, newState)
    {
      if (newState == true || confirm('Disable organization "' + name + '"?'))
      {
          $.ajax({type: 'POST', url: '@Url.Action("SetOrganizationApproved")', data: { q: id, approved: newState }, dataType: 'json',
              success: function(data) {
                load();
              }
          });
      }
    }

    function deleteOrg(id, name)
    {
        if (confirm('Completely remove organization "'+name+'"?'))
        {
          $.ajax({type: 'POST', url: '@Url.Action("DoDeleteOrganization")', data: { q: id }, dataType: 'json',
              success: function(data) {
                load();
              }
          });
        }
    }

    $(document).ready(function () {
        $('#table').tablesorter({ widgets: ['zebra'] });
        load();
    });
</script>

code/website/Views/Organizations/Settings.cshtml
@{
    ViewBag.Title = "Settings";
}

<h2>Settings</h2>
<div style=" border-radius:.5em; border:1px solid #999; padding:0 .5em .5em .5em">
<h4>Unit Status Types:</h4>
@{ Html.RenderPartial("_StatusTypes"); }
</div>

code/website/Views/Organizations/StatusForm.cshtml
@* Copyright 2011 Matt Cosand and others (see AUTHORS.TXT)
 *
 * This file is part of SARTracks.
 *
 *  SARTracks is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  SARTracks is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with SARTracks.  If not, see <http://www.gnu.org/licenses/>.
 *@
@model SarTracks.Website.Models.UnitStatusType

@using (Html.BeginForm("SaveStatus", "Organizations", FormMethod.Post, new { id = "StatusForm" }))
{
@Html.HiddenFor(f => f.Id)
<div>
@Html.LabelFor(f => f.Name)
@Html.TextBoxFor(f => f.Name)
@Html.ValidationMessageFor(f => f.Name)
</div>
    
    <div>
    @Html.LabelFor(f => f.IsActive)
    @Html.CheckBoxFor(f => f.IsActive)
    </div>
    <div>
    @Html.LabelFor(f => f.IsMissionQualified)
    @Html.CheckBoxFor(f => f.IsMissionQualified)
    </div>
}

code/website/Views/Organizations/StatusManagement.cshtml
@model SarTracks.Website.Models.UnitStatusType
@using SarTracks.Website.Models;

<div id="StatusDialog" title="Create Member Status Type" style="display:none;">
    <p class="validateTips"></p>

    <form method="post" id="NewMembershipForm" action="#">
    <input type="hidden" value="@Model.OrganizationId" name="OrganizationId" />
    </form>
</div>

<script type="text/javascript">
        setupFormDialog($('#StatusDialog'),
    450, 450,
    "Create Status",
    '@Url.Action("SubmitOrgStatus")',
    function (data) { loadStatus(); return true; } //on success update table with new object
);
</script>