code/website/ViewModels/RosterViewModel.cs
/* Copyright 2011 Matt Cosand and others (see AUTHORS.TXT)
 *
 * This file is part of SARTracks.
 *
 *  SARTracks is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  SARTracks is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with SARTracks.  If not, see <http://www.gnu.org/licenses/>.
 */
namespace SarTracks.Website.ViewModels
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Runtime.Serialization;
    
    [DataContract]
    public class RosterViewModel
    {
        [DataMember]
        public Guid Id { get; set; }

        [DataMember]
        public string FirstName { get; set; }
        
        [DataMember]
        public string LastName { get; set; }

        [DataMember]
        public string Designator { get; set; }

        [DataMember]
        public string Email { get; set; }

        [DataMember]
        public string Phone { get; set; }

        [DataMember]
        public string Status { get; set; }
    }
}

code/website/Controllers/UnitsController.cs
/* Copyright 2011 Matt Cosand and others (see AUTHORS.TXT)
 *
 * This file is part of SARTracks.
 *
 *  SARTracks is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  SARTracks is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with SARTracks.  If not, see <http://www.gnu.org/licenses/>.
 */
namespace SarTracks.Website.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using System.Web.Security;
    using SarTracks.Website.Models;
    using SarTracks.Website.Services;
    using SarTracks.Website.ViewModels;


    public class UnitsController : ControllerBase
    {
        public const string VIEWDATA_CANADDUSER = "canAddUser";

        //
        // GET: /Units/

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Authorize]
        public ActionResult Roster(Guid q)
        {
            if (!Permissions.HasPermission(PermissionType.ViewOrganizationDetail, q)) return GetLoginRedirect();

            Organization model;
            using (var ctx = GetRepository())
            {
                model = ctx.Organizations.Single(f => f.Id == q);
            }
            ViewData[UnitsController.VIEWDATA_CANADDUSER] = Permissions.HasPermission(PermissionType.AddOrganizationMembers, q);

            return View(model);
        }

        [HttpGet]
        public ActionResult RosterManagement(Guid q)
        {
            if (!Permissions.HasPermission(PermissionType.ViewOrganizationDetail, q)) return GetLoginError();

            UnitMembership model = new UnitMembership
            {
                Member = new SarMember(),
            };

            using (var ctx = GetRepository())
            {
                var org = ctx.Organizations.IncludePaths("UnitStatusTypes").Single(f => f.Id == q);
                model.Organization = org;
                model.OrganizationId = org.Id;
                model.Status = org.UnitStatusTypes.First();
            }

            return PartialView(model);
        }

        public enum RosterImportColumn
        {
            MemberId,
            LastName,
            FirstName,
            Designator,
            Gender,
            BirthDate,
            Street,
            City,
            State,
            ZIP,
            HomePhone,
            CellPhone,
            WorkPhone,
            Pager,
            Email,
            DateJoined,
            Status
        }

        [HttpGet]
        public ActionResult ImportRoster(Guid q)
        {
            if (!Permissions.HasPermission(PermissionType.AddOrganizationMembers, q)) return GetLoginRedirect();

            Organization org;
            using (var ctx = GetRepository())
            {
                org = ctx.Organizations.Single(f => f.Id == q);
            }
            ViewData["columnNames"] = Enum.GetNames(typeof(RosterImportColumn));

            return View(org);
        }

        [HttpPost]
        public ActionResult ImportRoster(Guid q, FormCollection fields)
        {
            // Provide a common way to abort this method while providing useful messages to the user
            Func<string, ActionResult> fail = x => { ViewData["error"] = x; return ImportRoster(q); };

            // Permission check
            if (!Permissions.HasPermission(PermissionType.AddOrganizationMembers, q)) return GetLoginRedirect();

            // Basic validation of file
            if (Request.Files.Count != 1)
            {
                throw new InvalidOperationException("Can only submit one roster");
            }

            Organization org;
            UnitStatusType defaultStatus;
            using (var ctx = this.GetRepository())
            {
                org = ctx.Organizations.IncludePaths("UnitStatusTypes").Single(f => f.Id == q);
                defaultStatus = org.UnitStatusTypes.First(f => f.IsActive && f.IsMissionQualified);
            }

            var postedFile = Request.Files[0];

            byte[] fileData = new byte[postedFile.ContentLength];

            // Read file as Excel spreadsheet
            ExcelFileType fileType;
            if (!Enum.TryParse<ExcelFileType>(System.IO.Path.GetExtension(postedFile.FileName).TrimStart('.'), true, out fileType))
            {
                return fail("Filename does not end in one of: ." + string.Join(", .", Enum.GetNames(typeof(ExcelFileType))));
            }

            ExcelFile file;
            try
            {
                file = ExcelService.Read(postedFile.InputStream, fileType);
            }
            catch
            {
                return fail(string.Format("Error reading {0} file \"{1}\"", fileType, postedFile.FileName));
            }

            ExcelSheet sheet = file.GetSheet(0);

            // Figure out the order of the columns, and which ones were included...
            Dictionary<RosterImportColumn, int> columnLookup = new Dictionary<RosterImportColumn, int>();

            // Figure out which columns the user included in the spreadsheet
            int col = -1;
            do
            {
                col++;
                string header = sheet.CellAt(0, col).StringValue;
                if (string.IsNullOrWhiteSpace(header))
                {
                    break;
                }

                RosterImportColumn column;
                if (Enum.TryParse<RosterImportColumn>(header, true, out column))
                {
                    if (columnLookup.ContainsKey(column))
                    {
                        return fail(string.Format("Found multiple '{0}' columns", column));
                    }
                    columnLookup.Add(column, col);
                }
            } while (col < 100);

            // Make sure the required columns are included
            if (!columnLookup.ContainsKey(RosterImportColumn.LastName))
            {
                return fail(string.Format("File does not contain required column '{0}'", RosterImportColumn.LastName));
            }

            int row = 0;
            string externalKeySource = string.Format("roster{0}", q);
            List<string> errors = new List<string>();

            // ### Start Processing Rows
            do
            {
                row++;

                // Get the lastname. Lastname is required - a column without indicates the end of the data
                string lastname = sheet.CellAt(row, columnLookup[RosterImportColumn.LastName]).StringValue;
                if (string.IsNullOrWhiteSpace(lastname))
                {
                    break;
                }

                using (var ctx = GetRepository())
                {
                    ctx.Organizations.Attach(org);

                    // If the spreadsheet supplies an external key, look the member up in the database.
                    string key = columnLookup.ContainsKey(RosterImportColumn.MemberId) ?
                        sheet.CellAt(row, columnLookup[RosterImportColumn.MemberId]).StringValue :
                        null;

                    SarMember member = null;
                    if (!string.IsNullOrWhiteSpace(key))
                    {
                        var query = from x in
                                        (from f in ctx.ExternalReferences where f.Source == externalKeySource && f.ExternalKey == key select f)
                                    join m in ctx.Members.IncludePaths("Addresses", "ContactInfo") on x.InternalKey equals m.Id into mbrs
                                    select mbrs;

                        member = query.SelectMany(f => f).FirstOrDefault();
                    }

                    // If the member was not found by external key, add it to this database.
                    if (member == null)
                    {
                        member = new SarMember();
                        ctx.Members.Add(member);

                        if (!string.IsNullOrWhiteSpace(key))
                        {
                            ctx.ExternalReferences.Add(new ExternalReference
                            {
                                Source = externalKeySource,
                                ExternalKey = key,
                                InternalKey = member.Id
                            });
                        }
                    }

                    // Some data is updated all the time.
                    // First and Last names are.
                    member.LastName = lastname;

                    member.FirstName = columnLookup.ContainsKey(RosterImportColumn.FirstName) ?
                        sheet.CellAt(row, columnLookup[RosterImportColumn.FirstName]).StringValue :
                        null;

                    // Birthdate is updated if the column exists.
                    // I think this is formatted differently than the FirstName because it was using more
                    // than one statement. Should be able to change it back.
                    if (columnLookup.ContainsKey(RosterImportColumn.BirthDate))
                    {
                        member.BirthDate = sheet.CellAt(row, columnLookup[RosterImportColumn.BirthDate]).DateValue;

code/website/Views/Units/ImportRoster.cshtml
@model SarTracks.Website.Models.Organization

@{
    ViewBag.Title = "Import Roster : " + Model.LongName;
}

<h2>Import Roster for @Model.LongName</h2>
<p>Use this page to quickly import your organization's roster into SARTracks.</p>
<p>Both Excel 97/2003 (.xls) and Excel 2007 (.xlsx) files are supported. Save your roster using the following columns.
Some columns are optional and can be omitted from the file. Headers should be placed on the first row and match the
column names below. Data begins on the second row.</p>

<table cellspacing="0" class="data-table">
<thead>
<tr>
@foreach (var col in (string[])ViewData["columnNames"])
{
    <th>@col</th>
}
</tr></thead>
</table>

<p>Download sample files: [ <a href="@Url.Content("~/Content/files/sample-roster-import.xlsx")">XLSX</a> ][
<a href="@Url.Content("~/Content/files/sample-roster-import.xls")">XLS</a> ]</p>

@{Html.BeginForm("ImportRoster", "Units", FormMethod.Post, new { enctype = "multipart/form-data" });}
<fieldset title="Upload Organization Roster" style="margin: 1.5em 0">
<label for="rosterFile">Roster File:</label><br />
<input type="file" name="rosterFile" id="rosterFile" /><br />
<input type="submit" id="sendRoster" value="Upload" />
</fieldset>
@{Html.EndForm();}

<table cellspacing="0" class="data-table">
<thead><tr><th>Column Name</th><th>Required Column?</th><th>Description</th></tr></thead>
<tbody>
<tr><td><strong>MemberId</strong></td><td>Optional</td>
<td>Unique identifier for the member in your organization's database. If you do not store your records in Access or other database software,
you likely won't use this column. This value will be used to correlate the member between the
two databases, even if his/her name or designator changes. If the MemberId is already in the SARTracks database, that record will be replaced
with the values in the uploaded file. <strong>Otherwise, new records are created for all rows in the file.</strong></td></tr>

<tr><td><strong>LastName</strong></td><td>Required</td>
<td>The last name (surname) of the member.</td></tr>

<tr><td><strong>FirstName</strong></td><td>Required</td>
<td>The member's preferred given name. Legal names, if different, may be entered later using the member's detailed record.
 If the member only has one name, it should be located in the LastName column; the FirstName column should be left blank.</td></tr>

<tr><td><strong>Designator</strong></td><td>Optional</td>
<td>A badge number or worker number issued to the member by a governing body.</td></tr>

<tr><td><strong>Gender</strong></td><td>Optional</td>
<td>The member's gender (Male/Female/Unknown). If the column is omitted or the row left blank, the database will record 'Unknown'.</td></tr>

<tr><td><strong>BirthDate</strong></td><td>Optional</td>
<td>The member's date of birth. Used for general reporting, such as distinction between adults and youths.</td></tr>

<tr><td><strong>Street<br />City<br />State<br />ZIP</strong></td><td>Optional</td>
<td>The address of the member's primary residence or mail stop.</td></tr>

<tr><td><strong>Home<br />Cell<br />Work<br />Pager</strong></td><td>Optional</td>
<td>Phone numbers of the member. If a number applies to more than one category (ex: Cell phone is used as home phone),
please record it only in the most appropriate column.</td></tr>

<tr><td><strong>Email</strong></td><td>Optional</td>
<td>The member's primary email address.</td></tr>

<tr><td><strong>DateJoined</strong></td><td>Optional</td>
<td>The date the member most recently joined the organization.</td></tr>

<tr><td><strong>Status</strong></td><td>Optional</td>
<td>The member's current status with the unit. If not included, will default to 'Active'.</td></tr>
</tbody>
</table>

code/website/Views/Units/ImportRosterResults.cshtml
@{
    ViewBag.Title = "Roster Import Results";
}

<h2>Roster Import Results</h2>
<p>Roster import completed with @ViewData["rows"] rows imported successfully, and @ViewData["errors"] failures. Details on
the failures, if any, have been emailed to you.</p>

code/website/Views/Units/Roster.cshtml
@* Copyright 2011 Matt Cosand and others (see AUTHORS.TXT)
 *
 * This file is part of SARTracks.
 *
 *  SARTracks is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  SARTracks is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with SARTracks.  If not, see <http://www.gnu.org/licenses/>.
 *@
@model SarTracks.Website.Models.Organization
@using SarTracks.Website.Controllers

@{
    ViewBag.Title = "Roster";
    ViewBag.Heading = @Model.Name + " Member Roster";
    bool canAdd = (bool?)ViewData[UnitsController.VIEWDATA_CANADDUSER] ?? false;
}

@if (canAdd)
{
<span class="AddMember ButtonLink"><img style="position:relative; top:4px; margin-top:-4px;" src="@Url.Content("~/content/images/add_member_24.png")" alt="Person" /> Add New Member</span>
<a href="@Url.Action("ImportRoster", new { q = @Model.Id })" class="ImportRoster ButtonLink"><img style="position:relative; top:4px; margin-top:-4px;" src="@Url.Content("~/content/images/add_member_24.png")" alt="Person" /> Import Roster</a>
}

<table cellspacing="0" class="data-table" id="table">
  <thead>
    <tr><th>Last Name</th><th>First Name</th><th>Designator</th><th>E-Mail</th><th>Primary Phone</th><th>Status</th></tr>
  </thead>
  <tbody data-bind="foreach: { data: members, afterRender: function() { updateSort($('#table')); }}">
    <tr>
        <td><a data-bind="attr: { href: '@Url.Action("Detail", "Members")/' + Id }, text: LastName"></a></td>
        <td><a data-bind="attr: { href: '@Url.Action("Detail", "Members")/' + Id }, text: FirstName"></a></td>
        <td data-bind="text: Designator"></td>
        <td data-bind="text: Email"></td>
        <td data-bind="text: Phone"></td>
        <td data-bind="text: Status"></td>
    </tr>
  </tbody>
  <tfoot>
  </tfoot>
</table>

<script type="text/html" id="row-template">

</script>

<script type="text/javascript">
    function RosterModel(rows) {
        var self = this;
        self.members = ko.observableArray(rows);
    }

    $(document).ready(function () {
        global_showProgress();
        $('#table').tablesorter({ widgets: ['zebra'], sortList: [[0,0],[1,0]]});

        $(".AddMember").click(function () {
            loadManagement('@Url.Action("RosterManagement")', { q: '@Model.Id' }, function () {
                var newMembership = new MembershipModel();
                newMembership.OrganizationId('@Model.Id');
                ko.applyBindings(newMembership, $("#MembershipDialog")[0]);
                $("#MembershipDialog").dialog("open");
            });
        });

        $.ajax({ type: 'POST', url: '@Url.Action("GetRosterList")', data: { q: '@Model.Id' }, dataType: 'json',
            success: function (data) {
                rosterModel = new RosterModel(data);
                ko.applyBindings(rosterModel, document.getElementById('table'));
            },
            complete: function () {
                global_hideProgress();
            }
        });
    });
</script>

code/website/Views/Units/RosterManagement.cshtml
@model SarTracks.Website.Models.UnitMembership
@using SarTracks.Website.Models;

<div id="MembershipDialog" title="Create Unit Membership" style="display:none;">
    <p class="validateTips"></p>

    <form method="post" id="NewMembershipForm" action="#">
    <input type="hidden" data-bind="value: OrganizationId" name="OrganizationId" />
    <input type="hidden" data-bind="value: Member.Id" name="Member.Id" />
    <div class="editor-label">  
    <label for="Member_FirstName">FirstName</label>
    </div>
    <div class="editor-field">
    <input type="text" data-bind="value: Member.FirstName" name="Member.FirstName">
    <span data-valmsg-replace="true" data-valmsg-for="Member.FirstName" class="field-validation-valid"></span>
    </div>
    <div class="editor-label">
    <label for="Member_LastName">LastName</label>
    </div>
    <div class="editor-field">
    <input type="text" data-bind="value: Member.LastName" name="Member.LastName">
    <span data-valmsg-replace="true" data-valmsg-for="Member.LastName" class="field-validation-valid"></span>
    </div>
    <div class="editor-label">
    <label for="Member_Gender">Gender</label>
    </div>
    <div class="editor-field">
    <select name="Member.Gender" data-bind="value: Member.Gender" data-val-required="The Gender field is required." data-val="true">
        <option>Unknown</option>
        <option selected="selected">Male</option>
        <option>Female</option>
    </select>
    <span data-valmsg-replace="true" data-valmsg-for="Member.Gender" class="field-validation-valid"></span>
    </div>
    <div class="editor-label">
    <label for="Member_BirthDate">BirthDate</label>
    </div>
    <div class="editor-field">
    <input type="text" data-bind="dateValue: Member.BirthDate" name="Member.BirthDate" id="Member_BirthDate" class="text-box single-line datepicker">
    <span data-valmsg-replace="true" data-valmsg-for="Member.BirthDate" class="field-validation-valid"></span>
    </div>
    <br>
    <fieldset>
        <legend>Membership with @Model.Organization.Name</legend>
        <div class="editor-label">
        <label for="Status">Current Status</label>
@*        @Html.DropDownListFor(m => m.Status.Id, new SelectList(Model.Organization.UnitStatusTypes.OrderByDescending(f => f.IsActive).ThenByDescending(f => f.IsMissionQualified), "Id", "Name", Model.Status.Id))*@
        <select name="Status.Id" data-bind="value: Status.Id">
        @foreach (var item in Model.Organization.UnitStatusTypes.OrderByDescending(f => f.IsActive).ThenBy(f => f.Name))
        {
            <option value="@item.Id">@item.Name</option>
        }
        </select>

        <span data-valmsg-replace="true" data-valmsg-for="Status" class="field-validation-valid"></span>
        </div>

        <div class="editor-label">
        <label for="WorkerNumber">Id/Card Number</label>
        <input type="text" data-bind="value: WorkerNumber" name="WorkerNumber" data-val="true" class="text-box single-line">
        <span data-valmsg-replace="true" data-valmsg-for="WorkerNumber" class="field-validation-valid"></span>
        </div>

        <div class="editor-label">
        <label for="Start">Effective Date</label>
        <input type="text" data-bind="dateValue: Start" name="Start" id="Start" data-val-required="The Start field is required." data-val="true" class="text-box single-line datepicker">
        <span data-valmsg-replace="true" data-valmsg-for="Start" class="field-validation-valid"></span>
        </div>
    </fieldset>
</form>
</div>

<script type="text/javascript">
    setupFormDialog($('#MembershipDialog'),
    450, 450,
    "Create User",
    '@Url.Action("SubmitUnitMembership")?mode=1',
    function (data) {
        rosterModel.members.push(data);
        return true; } //on success update table with new object
);

</script>